config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'users#index'

  resources :nominees

  resources :users do
    collection do
      post 'invite_user', to: 'users#invite_user'
      get 'history', to:'users#history'

    end
  end

  get 'invite', to: 'users#invite'
  get 'voting_page', to: 'users#voting_page'

  resources :categories do
    member do
      post 'like', to: "nominees#like"
      delete 'remove_nominee', to:"categories#remove_nominee"
    end
  end

  get 'result', to:"categories#result"
  get 'nominee_list' ,to: "nominees#nominee_list"
  get 'winner_show', to: "categories#winner_show"
  get 'check_category', to: "categories#check_category"
  get 'check_nominee', to: "nominees#check_nominee"
  get 'profile', to:"nominees#profile"
  get 'pdf_result', to:"categories#pdf_result"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/nominee.rb
class Nominee < ApplicationRecord

  has_and_belongs_to_many :categories
  has_many :votes
  has_many :users, through: :votes
  mount_uploader :picture, ::PictureUploader

  validates :name, presence: true
  validates :picture, presence: true
  validates :description, presence: true


  def vote_count(category)
    @votes=Vote.all.where(category_id: category.id)
    @votes.all.where(nominee_id: self.id).count
  end

  def self.get_nominee_name(id)
    self.find(id).name
  end


end

app/controllers/nominees_controller.rb
class NomineesController < ApplicationController

  def index
    @category = Category.new
    @categories = Category.all
  end

  def new
    @categories = Category.all.where(status: 'Active').map{|u| [u.name,u.id]}
    @nominee = Nominee.new
  end

  def create
    @category = Category.find(params[:category_id])
    @nominee = Nominee.new(nominee_params)
    @nominees = @category.nominees
    if Nominee.where(name: params[:nominee][:name]).present?
      if !@category.nominees.where(name: params[:nominee][:name]).present?
        flash.now[:alert] = 'Nominee is added'
        @category.nominees << @nominee
      else
      flash.now[:alert] = 'Nominee already exists in this category'
      end
    else
      flash.now[:alert] = 'Nominee is added'
      @nominee.save
      @category.nominees << @nominee
    end
    respond_to do |format|
      format.js
    end
  end

  def nominee_list
    @category = Category.find_by(id: params[:category])
    @nominees = @category.nominees
    respond_to do |format|
      format.js
    end
  end

  def like
    @vote = Vote.new
    @vote.user_id = current_user.id
    @vote.nominee_id = params[:nom_id]
    @vote.category_id = params[:id]
    if @vote.save
      respond_to do |format|
        format.js
      end
    end
  end

  # def check_nominee
  #   @category = Category.find_by(id: params[:category])
  #   byebug
  # end

  def profile
    @nominee = Nominee.find(params[:id])
  end

  private

   def nominee_params
    params.require(:nominee).permit(:name,:picture,:description)
  end

end

app/helpers/nominees_helper.rb
module NomineesHelper
end

app/views/nominees/_like_modal.html.erb
<div class="modal" id="myModal" role="dialog">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
         <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
         <h3 id="myModalLabel">Delete</h3>
      </div>
      <div class="modal-body" >
          <%= "Enter Team Name:" %>
           <input type="text" id="team_name">
      </div>
      <div class="modal-footer">

        <button class="btn btn-primary" data-dismiss="modal" aria-hidden="true">Close</button>
      </div>
    </div>
  </div>
</div>

app/views/nominees/_nominee_list.html.erb
<ul class="list-group list-group-flush">
  <% @nominees.each do |nominee| %>
    <li class="list-group-item"><%= link_to nominee.name %></li>
  <% end %>
</ul>

app/views/nominees/_nominees_list.html.erb
<% @nominees.each do|nominee| %>

  <div class="box box-primary">
    <div class="box-header with-border">
      <h3 class="box-title"><%= nominee.name %></h3>
    </div>
    <!-- /.box-header -->
    <!-- form start -->
    <form role="form">
      <div class="box-body">
        <div class="form-group">
          <label for="exampleInputEmail1">    <%= image_tag nominee.picture.url, size: "150x100"  %></label>

        </div>
        <div class="form-group">
          <label for="exampleInputPassword1"><%= nominee.description %></label>

        </div>
        <div class="form-group">
          <label for="exampleInputFile">Total Votes :<%= nominee.vote_count(@category) %></label>


        </div>

      </div>
      <!-- /.box-body -->

      <div class="box-footer">
       <p class="card-text"><%= link_to 'Delete', remove_nominee_category_path(@category,nominee_id: nominee.id), method: :delete,  data: { confirm: "You sure?" }, remote: true %></p>
      </div>
    </form>
  </div>

<% end %>

app/views/nominees/_vote_modal.html.erb
<div class="modal" id="show-modal-window_modal" role="dialog">
  <div class="modal-dialog">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h1 class="modal-title text-danger">SUCCESS</h1>
        </div>
        <div class="modal-body">
          <p>Your vote is successfully recorded!!! Thank you for spending your valuable time with us...</p>
        </div>
        <div class="modal-footer">
         <%= link_to 'OK', root_path, class: "btn btn-success" %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/nominees/create.js.erb
$('#nominee_form')[0].reset();
$('#flashDiv').html("<%= j render partial: 'layouts/flash_message' %>");
 $("#flashDiv" ).fadeOut(5000);
$('#nominees').html("<%= j render partial: 'nominees_list' %>");
<% if flash.any? %>
  <% flash.each do |message_type, message| %>
  alert(message_type);
  <% end %>
<% end %>

app/views/nominees/index.html.erb
<body class="hold-transition skin-blue sidebar-mini">
  <div class="wrapper">
    <header class="main-header">
      <%= render 'layouts/header'%>
    </header>

    <aside class="main-sidebar">
      <%= render 'layouts/side_bar'%>
    </aside>

    <div class="content-wrapper" style="min-height:84vh;">
      <section class="content-header">
        <h1>
          View Nominees
        </h1>
      </section>

      <section class="content">
        <div class="box">
          <div class="box-header with-border">
            <h3 class="box-title">
              <div class="form-group has-feedback">
                <%= form_for(@category) do |f| %>
                Select category<%= f.select(:id, @categories.all.collect {|p| [ p.name, p.id ]}, class: "form-control select2", include_blank:true)  %>
              </div>
            </h3>
          </div>
          <div class="box-body">
            <div id="nominees">
            </div>
            <% end %>
          </div>
        </div>
      </section>
    </div>



    <footer class="main-footer">
      <%= render 'layouts/footer'%>
    </footer>

  </div>
</body>
<script>
$('#category_id').change( function(){
$.ajax({
    url: "/nominee_list", type: "GET", data : { category: $(this).val()}
  });

});
</script>

app/views/nominees/like.js.erb
$('#show-modal-window').html("<%= escape_javascript(render 'vote_modal') %>");
$("#show-modal-window_modal").modal();

app/views/nominees/new.html.erb
<body class="hold-transition skin-blue sidebar-mini">
  <div class="wrapper">
    <header class="main-header">
      <%= render 'layouts/header'%>
     </header>

    <!-- =============================================== -->

    <!-- Left side column. contains the sidebar -->
    <aside class="main-sidebar">
    <%= render 'layouts/select_side_bar' %>
    </aside>

    <!-- =============================================== -->

    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper" style="min-height:84vh;">
      <!-- Content Header (Page header) -->
      <section class="content-header">
        <h1>
         Add Nominees
        </h1>
      </section>

      <section class="content">
        <div class="box">
          <div class="box-header with-border">
            <h3 class="box-title">
              you can add new nominees here...
            </h3>
          </div>
          <div class="box-body">
             <div class="register-box-body">
               <div class="row">
                  <div class="col-md-7">
                   <div id="flashDiv">
                   </div>
                    <%= form_for(@nominee, html: {id: "nominee_form"}, url: nominees_path(id: :category_id), validate: true, remote: true) do |f| %>
                      <%#= render 'category_error' %>
                      <div class="form-group has-feedback">
                        <label>Select category</label>
                        <%= select_tag(:category_id, options_for_select(@categories), class: "form-control select2")%>
                      </div>
                      <div class="form-group has-feedback">
                        <%= f.text_field :name, placeholder: "Nominee name", id: "nominee_name", class:"form-control", id: "nominee_name", validate: true %>
                      </div>
                      <div class="form-group has-feedback">
                        <%= f.file_field :picture, validate: true%>
                      </div>
                       <div class="form-group has-feedback">
                          <%= f.text_area :description, size: "24x6", class:"form-control", placeholder: "Description", validate: true%>
                      </div>
                      <div>
                        <%= f.submit "ADD NOMINEE", class: "btn btn-primary btn-block btn-flat" %>
                      </div>
                    <% end %>
                  </div>
                  <div class="col-md-5">

                  </div>
                </div>
                <div id="nominees">
            </div>
              </div>
            </div>
          </div>
        </section>
        </div>

    <footer class="main-footer">
      <%= render 'layouts/footer'%>
    </footer>
  </div>
</body>

<!-- <script>
$('#nominee_name').change( function(){
  var name = $(this).val();
  var category =$('#category_id').val();
  var result = $.ajax({
    url: "/check_nominee", type: "GET", data : { data_value: name, category: category}
  });
});

</script> -->
<script>
$('#category_id').change( function(){
$.ajax({
    url: "/nominee_list", type: "GET", data : { category: $(this).val()}
  });

});
</script>

app/views/nominees/nominee_list.js.erb
$('#nominees').html("<%= j render partial: 'nominees_list' %>");

app/views/nominees/profile.html.erb
<body class="hold-transition skin-blue sidebar-mini">
  <div class="wrapper">
    <header class="main-header">
    <%= render 'layouts/header' %>
    </header>

    <aside class="main-sidebar">
    <%= render 'layouts/select_side_bar' %>
    </aside>

    <div class="content-wrapper" style="min-height:84vh;">
      <section class="content-header">
        <h1>
          Welcome <%= current_user.full_name %>
        </h1>
      </section>

      <section class="content container-fluid">

        <div class="box box-info">
          <div class="box-header with-border">
            <h3 class="box-title"><%= @nominee.name %></h3>
          </div>
        </div>

        <section class="content">
          <div class="row">
            <div class="col-md-6">
             <!-- AREA CHART -->
              <div class="box box-primary">
                <div class="box-header with-border">
                  <h3 class="box-title">About</h3>
                  </div>
                  <div class="box-body">
                  <div class="chart">
                    <%= @nominee.description %>
                  </div>
                </div>
              </div>
            </div>
            <div class="col-md-6">
              <div class="box box-primary">
                <div class="box-header with-border">
                  <h3 class="box-title"></h3>
                </div>
                <div class="box-body">
                  <div class="chart">
                    <%= image_tag @nominee.picture.url, size: "500x500"  %>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </section>

      </section>

    </div>

    <footer class="main-footer">
      <%= render 'layouts/footer' %>
    </footer>
  </div>
</body>