config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'users#index'

  resources :nominees

  resources :users do
    collection do
      post 'invite_user', to: 'users#invite_user'
      get 'history', to:'users#history'

    end
  end

  get 'invite', to: 'users#invite'
  get 'voting_page', to: 'users#voting_page'

  resources :categories do
    member do
      post 'like', to: "nominees#like"
      delete 'remove_nominee', to:"categories#remove_nominee"
    end
  end

  get 'result', to:"categories#result"
  get 'nominee_list' ,to: "nominees#nominee_list"
  get 'winner_show', to: "categories#winner_show"
  get 'check_category', to: "categories#check_category"
  get 'check_nominee', to: "nominees#check_nominee"
  get 'profile', to:"nominees#profile"
  get 'pdf_result', to:"categories#pdf_result"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord

  belongs_to :role
  has_many :votes
  has_many :nominees, through: :votes
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable


  def check_liked?(user,category)
    @votes = Vote.all.where(category_id: category.id)
    if @votes.find_by(user_id: user.id).present?
      return true
    else
      return false
    end
  end

  def admin?
    if self.role_id == 1
      return true
    else
      return false
    end
  end

  def full_name
    [first_name,last_name].join(" ")
  end





end

app/controllers/users/confirmations_controller.rb
class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   @user = User.new
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :email, :password,
  #                          :password_confirmation,:last_name,:phone_number,:role_id])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end

  # def sign_up_params
  #   params.require(:user).permit(:first_name, :email, :password,
  #                           :password_confirmation,:last_name,:phone_number)
  # end

end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = current_user
  end

  def index
    @categories = Category.all.order(created_at: :desc)
    @categories_all = Category.all.order(created_at: :desc).page params[:page]
  end

  def invite
    @user = User.new
  end

  def edit
    @user = User.find(params[:id])
    authorize @user
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(account_update_params)
      redirect_to user_path
    end
  end

  def history
    @votes = current_user.votes
  end

  def voting_page
    @category = Category.find(params[:cat_id])
    @nominees = @category.nominees
    @user = current_user
    @winners = Vote.winner(@category)
  end

  def invite_user
    @mail = params["user"]["email"]
    @user = User.find_by(email: @mail)
    respond_to do |format|
      if @user.present?
        UserNotifierMailer.invite_user(@mail).deliver
        flash.now[:alert] = 'Mail sent successfully!!!'
        format.js
      else
        UserNotifierMailer.activate_user(@mail).deliver
        flash.now[:alert] = 'Mail sent successfully!!!'
        format.js
      end
    end
  end


  private
  def user_params
    params.require(:user).permit(:email)
  end
  def sign_up_params
    params.require(:user).permit(:first_name, :email, :password,
                            :password_confirmation,:last_name,:phone_number)
  end
  def account_update_params
    params.require(:user).permit(:first_name, :email, :password,
                            :password_confirmation,:last_name,:phone_number)
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_admin_index.html.erb
<section class="content container-fluid">
  <div class="box-body">
    <% @categories_all.each do|category| %>
      <div class="col-xs-6">
        <h3><%= category.name %></h3>
        <%= pie_chart Vote.where(category_id: category.id).group(:nominee_id).count, discrete: false %>
      </div>
    <% end %>
  </div>
  <%= paginate @categories_all %>
</section>

app/views/users/_users_index.html.erb
<section class="content-header">
  <h1>
   Welcome <%= current_user.full_name %>
  </h1>
</section>
<div id="flashDiv">
  <%= render 'layouts/flash_message' %>
</div>
<section class="content-header" style="text-align: center;">
  <h2>
   <%= " It's time to vote for your favorite personalities!!!." %>
  </h2>
</section>

<section class="content container-fluid">
  <div class="box-body">
    <% if current_user.admin? %>
    <% else %>
        <% @categories.each do|category| %>
        <div class="outer_card">
          <div class="card_category">
            <div class="card-body">
               <h4 class="card-title"><%= category.name %></h4>
               <p class="card-text"><%= category.end_date.strftime("Ends on %B %d %Y at %T:%M %p") %><br></p>
               <% if category.active? %>
               <%= link_to 'Vote Now!!!!', voting_page_path(cat_id: category.id), class: "btn btn-primary" %>
               <% else %>
               <%= link_to 'Expired', voting_page_path(cat_id: category.id), class: "btn btn-danger" %>
               <% end %>
            </div>
          </div>
        <% end %>
      </div>
      <% end %>
   </div>
</section>

app/views/users/edit.html.erb
<body class="hold-transition skin-blue sidebar-mini">
  <div class="wrapper">
    <header class="main-header">
    <%= render 'layouts/header' %>
    </header>

    <aside class="main-sidebar">
    <%= render 'layouts/select_side_bar' %>
    </aside>

    <div class="content-wrapper" style="min-height:84vh;">
      <section class="content-header">
        <h1>
          Welcome <%= current_user.full_name %>
        </h1>
      </section>

      <section class="content">
        <div class="box">
          <div class="box-header with-border">
            <h3 class="box-title">You can edit your profile here...</h3>
          </div>
          <div class="box-body">
            <div class="row">
             <div class="col-md-3">
            </div>
             <div class="col-md-6">
              <div class="register-box-body">
                <%= form_for(@user, html: {id: "category_form"}, validate: true) do |f| %>
                  <div id="error_div">
                  </div>
                  <div class="form-group has-feedback">
                  <label for="inputEmail3" class="col-sm-6 control-label">First Name</label>
                    <%= f.text_field :first_name, placeholder: "First name", class:"form-control", value: @user.first_name %>
                  </div>
                  <div class="form-group has-feedback">
                  <label for="inputEmail3" class="col-sm-6 control-label">Last Name</label>
                    <%= f.text_field :last_name, placeholder: "Last name", class:"form-control", value: @user.last_name %>
                  </div>
                  <div class="form-group has-feedback">
                  <label for="inputEmail3" class="col-sm-6 control-label">Phone Number</label>
                    <%= f.text_field :phone_number, placeholder: "Phone number", class:"form-control", value: @user.phone_number %>
                  </div>

                  <div>
                  <div class="row">
                    <div class="col-md-6">
                  <%= link_to "CANCEL",user_path, class: "btn btn-primary btn-block btn-flat" %>
                  </div>
                   <div class="col-md-6">
                    <%= f.submit "UPDATE PROFILE", class: "btn btn-primary btn-block btn-flat" %>
                    </div>
                    </div>
                  </div>
                <% end %>
              </div>
            </div>
            </div>
            <div class="col-md-3">
            </div>
            </div>
          </div>
      </section>
    </div>

    <footer class="main-footer">
      <%= render 'layouts/footer' %>
    </footer>

  </div>
</body>

app/views/users/history.html.erb
<body class="hold-transition skin-blue sidebar-mini">
  <div class="wrapper">
    <header class="main-header">
      <%= render 'layouts/header' %>
    </header>
    <!-- Left side column. contains the logo and sidebar -->
    <aside class="main-sidebar">
      <%= render 'layouts/select_side_bar' %>
    </aside>

    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper" style="min-height:84vh;">
      <section class="content-header">
        <h1>
          Welcome <%= current_user.full_name %>
        </h1>
      </section>

      <section class="content container-fluid">
        <table class="table table-hover">
          <thead>
            <tr>
              <th>Category</th>
              <th>Voted for</th>
              <th>Voted_at</th>
            </tr>
          </thead>
          <tbody>
            <% @votes.each do|vote| %>
            <tr class="info">
            <td><%= Category.get_category_name(vote.category_id) %></td>
             <td><%= Nominee.get_nominee_name(vote.nominee_id) %></td>
            <td><%=vote.created_at.strftime(" %B %d %Y at %T:%M %p") %></td>
            </tr>
            <% end %>
          </tbody>
        </table>
      </section>
    </div>

    <footer class="main-footer">
       <%= render 'layouts/footer' %>
    </footer>
  </div>
</body>

app/views/users/index.html.erb
<body class="hold-transition skin-blue sidebar-mini">
  <div class="wrapper">
    <header class="main-header">
    <%= render 'layouts/header' %>
    </header>

    <aside class="main-sidebar">
    <%= render 'layouts/select_side_bar' %>
    </aside>


    <div class="content-wrapper" style="min-height:84vh;">
    <% if current_user.admin? %>
    <div id= "admin_page">
    </div>
    <%= render 'admin_index'%>
    <% else %>
      <%= render 'users_index'%>
    <% end %>
    </div>

    <footer class="main-footer">
     <%= render 'layouts/footer' %>
    </footer>


  </div>
</body>

app/views/users/invite.html.erb
<body class="hold-transition skin-blue sidebar-mini">
  <div class="wrapper">
    <header class="main-header">
      <%= render 'layouts/header'%>
     </header>

    <!-- Left side column. contains the sidebar -->
    <aside class="main-sidebar">
    <%= render 'layouts/select_side_bar' %>
    </aside>

    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper" style="min-height:84vh;">
      <!-- Content Header (Page header) -->
      <section class="content-header">
        <h1>
         Invite Members
        </h1>
      </section>

      <section class="content">
        <div class="box">
          <div class="box-header with-border">
            <h3 class="box-title">
              you can invite new members to this site...
            </h3>
          </div>
          <div class="row">
            <div id="flashDiv">
            </div>
            <div class="col-md-3">
            </div>
            <div class="col-md-6">
              <div class="box-body">
                <%= form_for(@user,url: invite_user_users_path,validate: true, remote: true, html: {id: "invite_form"}) do |f| %>
                  <div class="form-group has-feedback">
                    <%= f.email_field :email, placeholder: "Enter email id", class:"form-control", validate: true %>
                  </div>
                  <%= f.submit "Invite", class:"btn btn-primary btn-block btn-flat" %>
                <% end %>
              </div>
            </div>
            <div class="col-md-3">
            </div>
          </div>
        </div>
      </section>
      <!-- /.content -->
    </div>
    <!-- /.content-wrapper -->
    <div class='clearfix'></div>
    <footer class="main-footer" style=" min-height: 70vh%;";>
      <%= render 'layouts/footer'%>
    </footer>

  </div>
</body>

app/views/users/invite_user.js.erb
$('#flashDiv').html("<%= j render partial: 'layouts/flash_message' %>");
$("#flashDiv" ).fadeOut(5000);

app/views/users/show.html.erb
<body class="hold-transition skin-blue sidebar-mini">
  <div class="wrapper">

  <header class="main-header">
    <%= render 'layouts/header' %>
  </header>

    <aside class="main-sidebar">
      <%= render 'layouts/select_side_bar' %>
    </aside>

    <div class="content-wrapper" style="min-height:84vh;">
      <section class="content-header">
        <h1>
          Welcome <%= current_user.full_name %>
        </h1>
      </section>

      <section class="content container-fluid">
        <div class="box box-info">
          <div class="box-header with-border">
            <h3 class="box-title">Profile</h3>
          </div>
          <div class="row">
            <div class= "col-md-3">
            </div>
             <div class= "col-md-6">
              <div class="box box-primary">
                <div class="box-body box-profile">

                  <h3 class="profile-username text-center"><%= @user.full_name %></h3>

                  <p class="text-muted text-center"></p>

                  <ul class="list-group list-group-unbordered">
                    <li class="list-group-item">
                      <b>First Name</b> <a class="pull-right"><%= @user.first_name %></a>
                    </li>
                    <li class="list-group-item">
                      <b>Last Name</b> <a class="pull-right"><%= @user.last_name %></a>
                    </li>
                    <li class="list-group-item">
                      <b>Phone number</b> <a class="pull-right"><%= @user.phone_number %></a>
                    </li>
                    <li class="list-group-item">
                      <b>Email</b> <a class="pull-right"><%= @user.email %></a>
                    </li>
                  </ul>

                  <a href="#" class="btn btn-primary btn-block"><b><%= link_to 'Edit Profile', edit_user_path(current_user) %></b></a>
                </div>
              </div>
              <div class= "col-md-3">
              </div>
            </div>

            <!-- /.box-body -->
          </div>
        </div>
      </section>
    </div>

    <footer class="main-footer">
      <%= render 'layouts/footer' %>
    </footer>

  </div>
</body>

app/views/users/voting_page.html.erb
<body class="hold-transition skin-blue sidebar-mini">

  <div class="wrapper">
    <header class="main-header">
      <%= render 'layouts/header' %>
    </header>

    <aside class="main-sidebar">
    <%= render 'layouts/select_side_bar' %>
    </aside>

    <div class="content-wrapper" style="min-height:84vh;">

      <section class="content-header">
        <h1>
          Welcome <%= current_user.full_name %>
        </h1>
      </section>

      <section class="content container-fluid">
        <h3><%= @category.name %></h3>
        <h5><%= @category.description %></h5>
        <div class="box-body">
          <div class="content-header">
            <% if @user.check_liked?(@user,@category) && @category.active? %>
              <h4 class="text-blue">You are already voted for this category!!!</h2>
            <% end %>
          </div>
          <div class="row">
            <div class="col-md-8">
              <% @nominees.each do|nominee| %>
                <div class="card img-circle">
                   <%= link_to image_tag( nominee.picture.url, size: "200x200", class: "img-circle"), profile_path(id: nominee.id) %>
                  <div class="card-body">
                    <h4 class="card-title"><%= nominee.name %></h4>
                    <% if !@user.check_liked?(@user,@category) && @category.active? %>
                       <%= link_to 'Vote Now',like_category_path(id: @category.id, nom_id: nominee.id), { method: :post,remote: true, class: "btn btn-success", 'data-toggle' =>  "modal", 'data-target' => '#show-modal-window'}  %>
                    <% end %>
                    <h4 class="card-title"> Votes :<%= nominee.vote_count(@category) %></h4>
                  </div>
                </div>
              <% end %>
            </div>

            <div class="col-md-4 text-align">
              <div class="panel card">
                <div class="card-img-top">
                  <h4 class="card-title"> WINNER !!!</h4>
                  <% if !@category.active? %>
                    <div class="row">
                      <% @winners.each do |winner| %>
                        <div class="col-md-6">
                          <%= image_tag winner.picture.url, size: "150x100"  %>
                          <div class="card-block">
                            <h4 class="card-title"><%= winner.name%></h4>
                            <h4 class="card-title">Total Votes : <%= winner.vote_count(@category)%></h4>
                          </div>
                        </div>
                      <% end %>
                    </div>
                  <% else %>
                    <div class="row">
                       <%= image_tag 'avatar.png', size: "200x200", class: "img-circle"  %>
                      <div class="card-block">
                        <h4 class="card-title"><%= '???'%></h4>
                      </div>
                    </div>
                  <% end %>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>

    </div>

    <footer class="main-footer">
       <%= render 'layouts/footer' %>
    </footer>

  </div>
</body>
<div id="show-modal-window">
</div>