config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'users#index'

  resources :nominees

  resources :users do
    collection do
      post 'invite_user', to: 'users#invite_user'
      get 'history', to:'users#history'

    end
  end

  get 'invite', to: 'users#invite'
  get 'voting_page', to: 'users#voting_page'

  resources :categories do
    member do
      post 'like', to: "nominees#like"
      delete 'remove_nominee', to:"categories#remove_nominee"
    end
  end

  get 'result', to:"categories#result"
  get 'nominee_list' ,to: "nominees#nominee_list"
  get 'winner_show', to: "categories#winner_show"
  get 'check_category', to: "categories#check_category"
  get 'check_nominee', to: "nominees#check_nominee"
  get 'profile', to:"nominees#profile"
  get 'pdf_result', to:"categories#pdf_result"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/category.rb
class Category < ApplicationRecord

  has_and_belongs_to_many :nominees
  has_many :votes

  validates :name, presence: true, uniqueness: true
  validates :end_date, presence: true
  validates :status, presence: true
  validates :description, presence: true
  paginates_per 2

 def active?
    if self.status == 'Active'
      return true
    else
      return false
    end
  end

  def check_category_liked?(user,category)
    @votes = Vote.all.where(category_id: category.id)
    if @votes.find_by(user_id: user.id).present?
      return true
    else
      return false
    end
  end

  def self.get_category_name(id)
    Category.find(id).name
  end





end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController


  def new
    @category = Category.new
    @categories = Category.all.order(created_at: :desc)
  end

  def create
    @category = Category.new(category_params)
    @categories = Category.all.order(created_at: :desc)
    if @category.save
      respond_to do |format|
        format.js
      end
    end
  end

  def edit
    @category = Category.find(params[:id])
  end

  def update
    @category = Category.find(params[:id])
    if @category.update_attributes(category_params)
      flash.now[:alert] = 'category updated'
      redirect_to categories_path
    end
  end

  def show
  end

  def index
    @categories = Category.all.order(created_at: :desc)
  end

  def destroy
    @category = Category.find(params[:id]).destroy
    @categories = Category.all.order(created_at: :desc)
    respond_to do |format|
      format.js
    end
  end

  def remove_nominee
    @category = Category.find(params[:id])
    @nominee = Nominee.find(params[:nominee_id])
    @category.nominees.delete(@nominee)
    @nominees = @category.nominees
     respond_to do |format|
      format.js
    end
  end

  def result
     @categories = Category.all.map{|u| [u.name,u.id]}
  end

  def winner_show
    @category = Category.find_by(id: params[:category])
    @winners = Vote.winner(@category)
    respond_to do |format|
      format.js
    end
  end

  def check_category
    @name = params[:data_value]
    @category = Category.find_by(name: @name)
    respond_to do |format|
      format.js
    end
  end

  def pdf_result
    @categories = Category.all.where(status: 'Expired')

    respond_to do |format|
        format.html
        format.pdf do
          pdf = Winners_Pdf.new(@categories)
          send_data pdf.render,
            filename: "order",
            type: 'application/pdf',
            disposition: 'inline'
        end
      end
  end


  private

  def category_params
    params.require(:category).permit(:name,:end_date,:description)
  end



end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_category_details.html.erb
<table class="table table-hover">
  <thead>
    <tr>
      <th>Name</th>
      <th>End Time</th>
      <th>Description</th>
    </tr>
  </thead>
  <tbody>
    <% @categories.each do|category| %>
      <tr>
        <td><%= category.name %></td>
        <td><%= category.end_date %></td>
        <td><%= category.description %></td>
        <% if category.active? %>
        <td><%= link_to 'Edit', edit_category_path(category) %></td>
        <% else %>
        <td style="color:red;"><%= 'Expired' %></td>
        <% end %>
        <td><%= link_to 'Delete', category_path(category), method: :delete , remote: true,  data: { confirm: "You sure?" }%></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/categories/_category_error.html.erb
<% if @category.errors.any? %>
  <ul class="errors">
    <% @category.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>
<% end %>

app/views/categories/_category_error_message.html.erb
<h4>Category name already exist!!!"</h4>

app/views/categories/_category_list.html.erb
<ul class="list-group list-group-flush">
  <% @categories.each do |category| %>
    <li class="list-group-item"><%= link_to category.name %></li>
  <% end %>
</ul>

app/views/categories/_winner_show.html.erb
<% if !@category.active? %>
  <div class="row">
    <div class="col-md-4">
    </div>
     <div class="col-md-4">
      <div class="box">
        <div class="box-header with-border">
          <h3 class="box-title">WINNER !!!</h3>
        </div>
        <div class="row">
          <% @winners.each do |winner| %>
            <div class="col-md-6">
              <%= image_tag winner.picture.url, size: "150x100"  %>
              <div class="card-block">
                <h4 class="card-title"><%= winner.name%></h4>
                <h4 class="card-title">Total Votes : <%= winner.vote_count(@category)%></h4>
              </div>
            </div>
          <% end %>
        </div>
        <div class="col-md-4">
        </div>
      </div>
    </div>
  </div>
<% else %>
  <h2> Voting Going On !!!</h2>
<% end %>

app/views/categories/check_category.js.erb
<% if @category.present? %>
  $('#category_error').html("<%= j render partial: 'category_error_message' %>");
<% end %>
$('#category_error').fadeOut(5000);

app/views/categories/create.js.erb
<% if @category.errors.any? %>
  $('#error_div').html("<%= j render partial: 'category_error' %>")
<% else %>
  $('#category_list').html("<%= j render partial: 'category_list' %>");
<% end %>
$('#category_form')[0].reset();

$('#error_div').fadeOut(5000);
$('#flashDiv').html("<%= j render partial: 'layouts/flash_message' %>");
$("#flashDiv" ).fadeOut(5000);

app/views/categories/destroy.js.erb
$('#category_list').html("<%= j render partial: 'category_details' %>")

app/views/categories/edit.html.erb
<body class="hold-transition skin-blue sidebar-mini">
  <div class="wrapper">

  <header class="main-header">
    <%= render 'layouts/header'%>
   </header>

  <!-- =============================================== -->

  <!-- Left side column. contains the sidebar -->
  <aside class="main-sidebar">
    <%= render 'layouts/side_bar'%>
  </aside>

  <!-- =============================================== -->

  <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper" style="min-height:84vh;">
    <section class="content-header">
      <h1>
       Edit Category
      </h1>
    </section>

    <section class="content">
      <div class="box">
        <div class="box-header with-border">
          <h3 class="box-title">You can edit category here...</h3>
        </div>
        <div class="box-body">
            <div class="register-box-body">
              <%= form_for(@category, html: {id: "category_form"}, validate: true) do |f| %>
                <div id="error_div">
                </div>
                <div class="form-group has-feedback">
                  <%= f.text_field :name, placeholder: "Category name", class:"form-control", value: @category.name %>
                </div>
                <div class="form-group has-feedback">
                  <%= f.datetime_select :end_date, class: "datepicker", placeholder: "End date"%>
                </div>
                <div class="form-group has-feedback">
                  <%= f.text_area :description, size: "24x6", class:"form-control", placeholder: "Description"%>
                </div>
                <div>
                  <%= f.submit "UPDATE CATEGORY", class: "btn btn-primary btn-block btn-flat" %>
                </div>
              <% end %>
            </div>
          </div>
        </div>
      </section>

    </div>


    <footer class="main-footer">
      <%= render 'layouts/footer'%>
    </footer>

  </div>
</body>

app/views/categories/index.html.erb
<body class="hold-transition skin-blue sidebar-mini">
  <div class="wrapper">

  <header class="main-header">
    <%= render 'layouts/header'%>
   </header>

  <aside class="main-sidebar">
    <%= render 'layouts/side_bar'%>
  </aside>

  <div class="content-wrapper" style="min-height:84vh;">

    <section class="content-header">
      <h1>
        View Categories
      </h1>
    </section>

    <section class="content">
      <div class="box">
        <div class="box-header with-border">
          <h3 class="box-title">You can edit or delete categories...</h3>
         <div id="flashDiv">

          </div>
        </div>
        <div class="box-body">
          <div id = "category_list">
            <%= render 'category_details' %>
          </div>
        </div>
      </div>
      </section>
    </div>

    <footer class="main-footer">
      <%= render 'layouts/footer'%>
    </footer>

  </div>
</body>

app/views/categories/new.html.erb
<body class="hold-transition skin-blue sidebar-mini">
  <div class="wrapper">
    <header class="main-header">
      <%= render 'layouts/header'%>
    </header>

  <!-- =============================================== -->

  <!-- Left side column. contains the sidebar -->
    <aside class="main-sidebar">
      <%= render 'layouts/side_bar'%>
    </aside>


    <div class="content-wrapper" style="min-height:84vh;">
      <section class="content-header">
        <h1>
          Add new Category
        </h1>
      </section>

      <section class="content">
        <div class="box">
          <div class="box-header with-border">
            <h3 class="box-title">You can add new category here...</h3>
          </div>
          <div class="box-body">
            <div class="register-box-body">
              <div class="row">
                <div class="col-md-7">
                  <div id="error_div">

                  </div>
                  <%= form_for @category,url: categories_path, method: :post, html: {id: "category_form"}, validate: true, remote: true do |f| %>
                    <%#= render 'category_error' %>
                    <div class="form-group has-feedback">
                      <%= f.text_field :name, placeholder: "Category name", class:"form-control", id: 'category_name' %>
                    </div>
                     <div id="category_error"></div>
                    <div class="form-group has-feedback">
                      <%= f.datetime_select :end_date, id: "datepicker", placeholder: "End date"%>
                    </div>
                    <div class="form-group has-feedback">
                      <%= f.text_area :description, size: "24x6", class:"form-control", placeholder: "Description"%>
                    </div>
                    <div>
                      <%= f.submit "ADD CATEGORY", class: "btn btn-primary btn-block btn-flat" %>
                    </div>
                  <% end %>
                </div>
                <div class="col-md-5">
                  <div class="card" style="max-width: 20rem;">
                    <div class="card-header">
                      <h2>Category List</h2>
                    </div>
                    <div id = "category_list">
                      <%= render 'category_list' %>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>
    </div>
    <footer class="main-footer">
      <%= render 'layouts/footer'%>
    </footer>
  </div>
</body>

<script>
$('#category_name').change( function(){
  var name = $(this).val();
  console.log(name);
  var result = $.ajax({
    url: "/check_category", type: "GET", data : { data_value: name}
  });
});


$( "#datepicker" ).datepicker({
      dateFormat: 'dd-mm-yy',
      changeMonth: true,
      changeYear: true,
      yearRange: '1990:' + (new Date).getFullYear()    });

</script>

app/views/categories/remove_nominee.js.erb
$('#nominees').html("<%= j render partial: 'nominees/nominees_list' %>");

app/views/categories/result.html.erb
<body class="hold-transition skin-blue sidebar-mini">
  <div class="wrapper">
    <header class="main-header">
      <%= render 'layouts/header'%>
     </header>

    <!-- Left side column. contains the sidebar -->
    <aside class="main-sidebar">
    <%= render 'layouts/select_side_bar' %>
    </aside>

  <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper" style="min-height:84vh;">
      <!-- Content Header (Page header) -->
      <section class="content-header">
        <h1>
       Result
        </h1>
      </section>

      <section class="content">
        <div class="box">
          <div class="box-header with-border">
            <h3 class="box-title">
              you can check result here...
            </h3>
            <%= link_to 'Generate Result(PDF)',pdf_result_path(:format => 'pdf'), target: '_blank', class: "btn btn-primary pull-right" %>
          </div>
          <div class="box-body">
            <div class="row">
              <div class="col-md-3">
              </div>
              <div class="col-md-6">
                <div class="form-group has-feedback">
                  Select category
                  <%= select_tag(:category_id, options_for_select(@categories),include_blank:true, class: "form-control select2")%>
                </div>
              </div>
              <div class="col-md-3">
              </div>
            </div>
          </div>
          <div class="box-body">
            <div id="result_view">
            </div>
           </div>
        </div>
      </section>
      <!-- /.content -->
    </div>
    <!-- /.content-wrapper -->

    <footer class="main-footer">
      <%= render 'layouts/footer'%>
    </footer>
  </div>
</body>

<script>
$('#category_id').change( function(){
$.ajax({
    url: "/winner_show", type: "GET", data : { category: $(this).val()}
  });

});
</script>

app/views/categories/winner_show.js.erb
$('#result_view').html("<%= j render partial: 'winner_show' %>");