config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'users#index'

  resources :nominees

  resources :users do
    collection do
      post 'invite_user', to: 'users#invite_user'
      get 'history', to:'users#history'

    end
  end

  get 'invite', to: 'users#invite'
  get 'voting_page', to: 'users#voting_page'

  resources :categories do
    member do
      post 'like', to: "nominees#like"
      delete 'remove_nominee', to:"categories#remove_nominee"
    end
  end

  get 'result', to:"categories#result"
  get 'nominee_list' ,to: "nominees#nominee_list"
  get 'winner_show', to: "categories#winner_show"
  get 'check_category', to: "categories#check_category"
  get 'check_nominee', to: "nominees#check_nominee"
  get 'profile', to:"nominees#profile"
  get 'pdf_result', to:"categories#pdf_result"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_flash_message.html.erb
<% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type %>">
     <button class="close" data-dismiss="alert">×</button>
    <%= message %>
  </div>
<% end %>

app/views/layouts/_footer.html.erb
<strong>Copyright &copy; 2014-2017 .</strong>
All rights reserved.

app/views/layouts/_header.html.erb
<!-- Logo -->
    <a class="logo">
      <!-- mini logo for sidebar mini 50x50 pixels -->
      <span class="logo-mini"><b>ONLINE</b></span>
      <!-- logo for regular state and mobile devices -->
      <span class="logo-lg"><b>ONLINE VOTING</b> </span>
    </a>
    <!-- Header Navbar: style can be found in header.less -->
    <nav class="navbar navbar-static-top">
      <!-- Sidebar toggle button-->
      <a href="#" class="sidebar-toggle" data-toggle="push-menu" role="button">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>

      <div class="navbar-custom-menu">
        <ul class="nav navbar-nav">
          <!-- Messages: style can be found in dropdown.less-->
          <li class="dropdown messages-menu">
            <!-- <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              <i class="fa fa-envelope-o"></i>
              <span class="label label-success">4</span>
            </a> -->

          </li>

          <!-- Tasks: style can be found in dropdown.less -->

          <!-- User Account: style can be found in dropdown.less -->
          <li class="dropdown user user-menu">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              <img src="<%= asset_path 'user2-160x160.jpg' %>" class="user-image" alt="User Image">
              <span class="hidden-xs"><%#= current_user.full_name %></span>
            </a>
            <ul class="dropdown-menu">
              <!-- User image -->
              <li class="user-header">
                <img src="<%= asset_path 'user2-160x160.jpg' %>" class="img-circle" alt="User Image">


              </li>
              <!-- Menu Body -->
              <li class="user-body">

                <!-- /.row -->
              </li>
              <!-- Menu Footer-->
              <li class="user-footer">
                <div class="pull-left">
                  <%#= link_to "Profile", profile_user_path(current_user), class: "btn btn-default btn-flat" %>
                </div>
                <div class="pull-right">
                <%= link_to "Log out", destroy_user_session_path, method: :delete, class: 'btn btn-default btn-flat'  %>
                </div>
              </li>
            </ul>
          </li>
          <!-- Control Sidebar Toggle Button -->

        </ul>
      </div>
    </nav>

app/views/layouts/_outer_header.html.erb
<div class="page-header bg-dark">
  <h1 class="text-primary">ONLINE VOTING </h1>
</div>

app/views/layouts/_select_side_bar.html.erb
 <% if current_user.admin? %>
    <%= render 'layouts/side_bar' %>
    <%else %>
    <%= render 'layouts/user_side_bar' %>
<% end %>

app/views/layouts/_side_bar.html.erb
<section class="sidebar">

  <div class="user-panel">
    <div class="pull-left image">
      <img src="<%= asset_path 'user2-160x160.jpg' %>" class="img-circle" alt="User Image">
    </div>
    <div class="pull-left info">
      <p><%=current_user.full_name%></p>
      <a href="#"><i class="fa fa-circle text-success"></i> Online</a>
    </div>
  </div>

 <ul class="sidebar-menu" data-widget="tree">
   <li><%= link_to 'Home',  root_path %></li>
    <li><%= link_to 'Add Category',  new_category_path %></li>
    <li><%= link_to 'View Categories', categories_path %></li>
    <li><%= link_to 'Add Nominees',  new_nominee_path %></li>
    <li><%= link_to 'View Nominees', nominees_path %></li>
    <li><%= link_to 'Invite Users',  invite_path %></li>
    <li><%= link_to 'Result',  result_path %></li>
  </ul>

</section>

app/views/layouts/_user_side_bar.html.erb
<section class="sidebar">
      <!-- Sidebar user panel -->
      <div class="user-panel">
        <div class="pull-left image">
          <img src="<%= asset_path 'user2-160x160.jpg' %>" class="img-circle" alt="User Image">
        </div>
        <div class="pull-left info">
          <p><%=current_user.full_name%></p>
          <a href="#"><i class="fa fa-circle text-success"></i> Online</a>
        </div>
      </div>
      <ul class="sidebar-menu" data-widget="tree">
        <li class="header">MAIN NAVIGATION</li>
           <li><%= link_to 'Home',  root_path %></li>
          <li><%= link_to 'Profile',  user_path(current_user) %></li>
          <li><%= link_to 'History',  history_users_path %></li>

        </ul>
    </section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bootapp</title>
     <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
     <link rel="stylesheet"
        href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic">
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag "http://www.google.com/jsapi", "chartkick" %>

  </head>
    <% if !user_signed_in? %>
    <%= render 'layouts/outer_header'%>
  <% end %>

    <%= yield %>



  <% if !user_signed_in? %>
    <%= render 'layouts/outer_footer'%>
  <% end %>
</html>